version: 2

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - &build
    id: auth-aws
    main: ./auth/aws/cmd
    binary: openbao-plugin-auth-aws
    targets:
      - linux_amd64_v1
      - linux_arm_6
      - linux_arm64_v8.0
      - linux_ppc64le
      - linux_riscv64_rva20u64
      - linux_s390x
      - darwin_amd64_v1
      - darwin_arm64_v8.0
      - dragonfly_amd64_v1
      - freebsd_amd64_v1
      - freebsd_arm_6
      - freebsd_arm64_v8.0
      - illumos_amd64_v1
      - netbsd_amd64_v1
      - netbsd_arm_6
      - netbsd_arm64_v8.0
      - openbsd_amd64_v1
      - openbsd_arm_6
      - openbsd_arm64_v8.0
      - windows_amd64_v1
      - windows_arm_6
      - windows_arm64_v8.0

  - id: auth-azure
    main: ./auth/azure/cmd
    binary: openbao-plugin-auth-azure
    <<: *build

  - id: auth-gcp
    main: ./auth/gcp/cmd
    binary: openbao-plugin-auth-gcp
    <<: *build

  - id: secrets-aws
    main: ./secrets/aws/cmd
    binary: openbao-plugin-secrets-aws
    <<: *build

  - id: secrets-azure
    main: ./secrets/azure/cmd
    binary: openbao-plugin-secrets-azure
    <<: *build

  - id: secrets-gcp
    main: ./secrets/gcp/cmd
    binary: openbao-plugin-secrets-gcp
    <<: *build

  - id: secrets-gcpkms
    main: ./secrets/gcpkms/cmd
    binary: openbao-plugin-secrets-gcpkms
    <<: *build
