name: push-image

on:
  workflow_dispatch:
    inputs:
      plugin:
        description: Plugin to build
        required: true
        type: string
      version:
        description: Version to publish
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.matrix.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: matrix
        run: |
          make ci-targets >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix:
        target: ${{ fromJSON(needs.matrix.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build plugin
        run: |
          make build PLUGIN=${{ inputs.plugin }} TARGET=${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-${{ matrix.target }}
          path: bin/*
  push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install buildah
        run: |
          sudo apt-get -y update
          sudo apt-get -y install buildah
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin
          pattern: plugin-*
          merge-multiple: true
      - name: Push image
        run: |
          make -j $(nproc) push PLUGIN=${{ inputs.plugin }} VERSION=${{ inputs.version }}
        env:
          GH_TOKEN: ${{ github.token }}
